create table if not exists customer
(
    id           bigint generated by default as identity
        primary key,
    credit_limit numeric(38, 2),
    name         varchar(255)
);

create table if not exists ing_user
(
    id          bigint generated by default as identity
        primary key,
    customer_id varchar(255),
    password    varchar(255),
    username    varchar(255)
);

create table if not exists loan
(
    id                    bigint generated by default as identity
        primary key,
    amount                numeric(38, 2),
    create_date           timestamp(6),
    customer_id           bigint,
    is_paid               boolean,
    number_of_installment integer
);

create table if not exists loan_installment
(
    id             bigint generated by default as identity
        primary key,
    amount         numeric(38, 2),
    default_amount numeric(38, 2),
    due_date       date,
    is_paid        boolean,
    loan_id        bigint,
    payment_date   date
);

create table if not exists role
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table if not exists user_roles
(
    user_id bigint not null
        constraint fk7n7bhnnrsm7rfhumnbqgk8l8u
            references ing_user,
    role_id bigint not null
        constraint fkrhfovtciq1l558cw6udg0h0d3
            references role,
    primary key (user_id, role_id)
);



-- Role tablosuna veri ekleme
INSERT INTO role (name) VALUES ('ROLE_ADMIN'), ('ROLE_USER')
ON CONFLICT (name) DO NOTHING;

-- User tablosuna veri ekleme
INSERT INTO ing_user (username, password) 
VALUES ('admin', '$2a$12$GVeK33iT3o.777rr8ZAYPeHf9yRs6SoeErsZa/AM/NuHg2.nosZ0W')
ON CONFLICT (username) DO NOTHING;

INSERT INTO ing_user (username, customer_id, password) 
VALUES 
    ('user1', '1', '$2a$12$GVeK33iT3o.777rr8ZAYPeHf9yRs6SoeErsZa/AM/NuHg2.nosZ0W'),
    ('user2', '2', '$2a$12$GVeK33iT3o.777rr8ZAYPeHf9yRs6SoeErsZa/AM/NuHg2.nosZ0W'),
    ('user3', '3', '$2a$12$GVeK33iT3o.777rr8ZAYPeHf9yRs6SoeErsZa/AM/NuHg2.nosZ0W')
ON CONFLICT (username) DO NOTHING;

-- User-Roles ilişkisini ekleme
INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id
FROM ing_user u, role r
WHERE u.username = 'admin' AND r.name = 'ROLE_ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM ing_user u, role r
WHERE u.username IN ('user1', 'user2', 'user3') AND r.name = 'ROLE_USER'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Customer verilerini ekleme
INSERT INTO customer (name, credit_limit) 
VALUES 
    ('peace', 10000),
    ('war', 140000),
    ('orange', 600000)
ON CONFLICT (name) DO NOTHING;
