spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_module
    username: ${DB_USERNAME:postgress}
    password: ${DB_PASSWORD:postgress}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG
